<?php

/*
 * devirion
 *
 * Copyright (C) 2016 Poggit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace poggit\virion\devirion;

use ClassLoader;

class VirionClassLoader extends \BaseClassLoader{
	private $messages;

	private $antigenMap;
	private $mappedClasses;

	public function __construct(ClassLoader $parent = null){
		parent::__construct($parent);
		$this->messages = new \Threaded();
		$this->antigenMap = new \Threaded;
		$this->mappedClasses = new \Threaded;
	}

	public function addAntigen(string $antigen, string $path){
		$this->antigenMap[$path] = $antigen;
	}

	public function getKnownAntigens() : array{
		$antigens = [];
		foreach($this->antigenMap as $antigen){
			$antigens[] = $antigen;
		}
		return $antigens;
	}

	public function findClass($class){
		$baseName = str_replace("\\", DIRECTORY_SEPARATOR, $class);
		foreach($this->antigenMap as $path => $antigen){
			if(substr(strtolower($class), 0, strlen($antigen)) === strtolower($antigen)){
				if(PHP_INT_SIZE === 8 and file_exists($path . DIRECTORY_SEPARATOR . $baseName . "__64bit.php")){
					$this->mappedClasses[$class] = $antigen;
					return $path . DIRECTORY_SEPARATOR . $baseName . "__64bit.php";
				}elseif(PHP_INT_SIZE === 4 and file_exists($path . DIRECTORY_SEPARATOR . $baseName . "__32bit.php")){
					$this->mappedClasses[$class] = $antigen;
					return $path . DIRECTORY_SEPARATOR . $baseName . "__32bit.php";
				}elseif(file_exists($path . DIRECTORY_SEPARATOR . $baseName . ".php")){
					$this->mappedClasses[$class] = $antigen;
					return $path . DIRECTORY_SEPARATOR . $baseName . ".php";
				}
				$this->messages[] = "DEVirion detected an attempt to load class $class, matching a known antigen but does not exist. Please note that this reference might be shaded in virion building and may fail to load.\n";
			}
		}
		return null;
	}

	public function loadClass($name){
		try{
			return parent::loadClass($name); // TODO: Change the autogenerated stub
		}catch(\ClassNotFoundException $e){
			return null;
		}
	}

	public function getSourceViralAntigen(string $loadedClass){
		return $this->mappedClasses[$loadedClass] ?? null;
	}

	public function getMessages() : \Threaded{
		return $this->messages;
	}
}
